[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
contract = "7cBTgEf3vCgNqqp63wNAPFhXK2MDAsRz7co4kCtXJuNp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/bugra/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
